server:
  port: 8502

#Eureka Server üzerinde servisimin adı nasıl görünsün?
spring:
  application:
    name: ticket-service
  datasource:
    url: jdbc:mysql://localhost:3306/microserviceapp
    username: root
    password: microservice-app
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update
  rabbitmq:
    username: haydikodlayalim
    password: haydikodlayalim
  cloud:
    stream:
      bindings:
        output:
          destination: msqueue

#Git 8500 daki eureka ya kendini bağla
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8500/eureka/