server:
  port: 8503

#Eureka Server üzerinde servisimin adı nasıl görünsün?
spring:
  application:
    name: notification-service
  rabbitmq:
    username: haydikodlayalim
    password: haydikodlayalim
  cloud:
    stream:
      bindings:
        input:
          destination: msqueue
#Kuyruk adı : msqueue


#Git 8500 daki eureka ya kendini bağla
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8500/eureka/